<?php

$str = 'The reader, who takes up these volumes, in expectation of finding an imaginary and romantic picture of things which never had an existence, will probably lay them aside, disappointed. The work is exactly what it professes to be in its title-page—a narrative. As it relates, however, to matters which may not be universally understood, especially by the more imaginative sex, some of whom, under the impression that it is a fiction, may be induced to read the book, it becomes the interest of the author to explain a few of the obscurities of the historical allusions. He is admonished to discharge this duty, by the bitter cup of experience, which has often proved to him, that however ignorant the public may be of any thing before it is presented to their eyes, the instant it has been subjectedto that terrible ordeal, they, individually and collectively, and he may add, intuitively, know more of it than the agent of the discovery; and yet, that, in direct opposition to this incontrovertible fact, it is a very unsafe experiment either for a writer or a projector to trust to the inventive powers of any one but himself. Therefore, nothing which can well be explained, should be left a mystery. Such an expedient would only impart a peculiar pleasure to readers of that description, who find a strange gratification in spending more of their time in making books, than of their money in buying them. With this preliminary explanation of his reasons for introducing so many unintelligible words, in the very threshold of his undertaking, the author will commence his task. Of course, nothing will, or need be told, with which any one, in the smallest degree acquainted with Indian antiquities, is not already familiar.
The greatest difficulty with which the student of Indian history has to contend, is the utter confusion that pervades the names. When, however, it is recollected, that the Dutch, the English, and the French, each took a conquerors liberty in this particular; that the natives themselves not only speak different languages, and even dialects of those languages, but that they are also fond of multiplying their appellations, the difficulty is more a matter of regret than of surprise. It is hoped, that whatever other faults may exist in the following pages, their obscurity will be thought to arise from this fact.
The Europeans found that immense region which lies between the Penobscot and the Potomac, the Atlantic and the Mississippi, in the possession of a people who sprang from the same stock. In one or two points of this immense boundary, their limits may have been a little extended or curtailed, by the surrounding nations; but such, in general terms, was the extent of their territory. The generic name of this people was the Wapanachki. They werefond, however, of calling themselves the “Lenni Lenape,” which of itself signifies, an “unmixed people.” It would far exceed the information of the author, to enumerate a moiety of the communities, or tribes, into which this race of beings was subdivided. Each tribe had its name, its chiefs, its hunting grounds, and, frequently, its dialect. Like the feudal princes of the old world, they fought among themselves, and exercised most of the other privileges of sovereignty. Still, they admitted the claims of a common origin, a similar language, and of that moral interest, which was so faithfully and so wonderfully transmitted through their traditions. One branch of this numerous people was seated on a beautiful river, known as the “Lenapewihittuck,” where the “long house,” or Great Council Fire, of the nation was universally admitted to be established.
The tribe that possessed the country which now composes the south-western parts of New-England, and that portion of New-York that lies east of the Hudson, andthe country even much farther to the south, was a mighty people, called the “Mahicanni,” or, more commonly, the “Mohicans.” The latter word has since been corrupted by the English, into “Mohegan.”
The Mohicans were again subdivided. In their collective capacity, they even disputed the point of antiquity with their neighbours, who possessed the “long house;” but their claim to be the “eldest son” of their “grandfather,” was freely allowed. Of course, this portion of the original proprietors of the soil was the first dispossessed by the whites. The few of them that now remain, are chiefly scattered among other tribes, and retain no other memorials of their power and greatness, than their melancholy recollections.
The tribe that guarded the sacred precincts of the council house, was distinguished for ages by its flattering title of the “Lenape;” but after the English changed the appellation of their river to “Delaware,” they came gradually to be known by thesame name. In the use of these terms, however, great delicacy of perception was observed among themselves. These shades of expression pervade their language, tempering all their communications, and frequently imparting its pathos or energy to their eloquence.
For many hundreds of miles along the northern boundaries of the Lenape, was seated another people, similarly situated as to subdivisions, descent, and language. They were called by their neighbours the “Mengwe.” These northern savages were, for a time, however, less powerful, and less united, than the Lenape. In order to obviate this disadvantage, five of the most powerful and warlike of their tribes, who lay nearest to the council house of their enemies, confederated for the purposes of mutual defence; being, in truth, the oldest United Republics of which the history of North America furnishes any evidence. These tribes were the Mohawks, the Oneidas, the Senecas, the Cayugas, and the Onondagas. At a later day, a straggling band of their race, which had “gone nigher to the sun,” was reclaimed, and admitted into a full communion of all their political privileges. This tribe (the Tuscarora) increased their number so far, that the English changed the appellation they had given the confederation, from the “Five” to the “Six Nations.” It will be seen, in the course of the narrative, that the word nation is sometimes applied to a community, and sometimes to the people, in their most extended sense. The Mengwe were often called by their Indian neighbours, the “Maquas,” and frequently, by way of contempt, “Mingoes.” The French gave them the name of “Iroquois,” which was probably a corruption of one of their own terms.
There is a well authenticated and disgraceful history of the means by which the Dutch on one side, and the Mengwe on the other, succeeded in persuading the Lenape to lay aside their arms, trusting their defence entirely to the latter, and becoming,in short, in the figurative language of the natives, “women.” The policy on the part of the Dutch was a safe one, however generous it may have been. From that moment may be dated the downfal of the greatest and most civilized of the Indian nations, that existed within the limits of the present United States. Robbed by the whites, and murdered and oppressed by the savages, they lingered for a time around their council-fire, but finally broke off in bands, and sought refuge in the western wilds. Like the lustre of the dying lamp, their glory shone the brightest as they were about to become extinct.
Much more might be said concerning this interesting people, especially of their later history, but it is believed not to be essential to the plan of the present work. Since the death of the pious, the venerable, and the experienced Heckewelder, a fund of information of this nature has been extinguished, which, it is feared, can never again be collected in one individual. Helaboured long and ardently in their behalf, and not less to vindicate their fame, than to improve their moral condition.
With this brief introduction to his subject, then, the author commits his book to the reader. As, however, candour, if not justice, requires such a declaration at his hands, he will advise all young ladies, whose ideas are usually limited by the four walls of a comfortable drawing room; all single gentlemen, of a certain age, who are under the influence of the winds; and all clergymen, if they have the volumes in hand, with intent to read them, to abandon the design. He gives this advice to such young ladies, because, after they have read the book, they will surely pronounce it shocking; to the bachelors, as it might disturb their sleep; and to the reverend clergy, because they might be better employed';

for ($i = 0; $i < strlen($str); $i++) {


    if ($i % 100 == 0 && $i != 0) {
        echo $str[$i] . "<br>";
    } else {
        echo $str[$i];
    }


}



